
import { Branch } from './types';

export const BRANCHES: Branch[] = [
  { id: 'branch-1', name: 'Downtown Branch', location: 'City Center' },
  { id: 'branch-2', name: 'Westside Branch', location: 'Shopping Mall' },
  { id: 'branch-3', name: 'Airport Branch', location: 'Terminal 3' },
];

export const APP_NAME = 'FinAI Manager';

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    controlPanel: 'Control Panel',
    reports: 'Reports',
    systemSettings: 'System Settings',
    signOut: 'Sign Out',
    loggedInAs: 'Logged in as',
    headOffice: 'Head Office Admin',
    branchUser: 'Branch User',
    revenue: 'Gross Revenue',
    costs: 'Operational Costs',
    profit: 'Net Profitability',
    margin: 'Profit Margin',
    history: 'Regional Performance Trends',
    comparison: 'Multi-Branch Comparison',
    aiAudit: 'AI Regional Audit',
    settings: 'Settings',
    language: 'Language',
    arabic: 'العربية (Arabic)',
    english: 'English',
    uaeTime: 'UAE Time',
    branchRanking: 'Branch Profit Ranking',
    ledger: 'Core Ledger',
    revenueStream: 'Revenue Stream',
    commit: 'Commit Statement',
    export: 'Export CSV',
    print: 'Print PDF',
    dateRef: 'Date / Reference',
    origin: 'Origin',
    status: 'Status',
    noData: 'No Matching Ledger Entries Found',
    auditPass: 'Audit Pass',
    flagged: 'Flagged',
    salesBreakdown: 'Sales Breakdown',
    expenseBreakdown: 'Expense Breakdown',
    totalDailySales: 'Total Daily Sales',
    totalDailyExpenses: 'Total Daily Expenses',
    recordDetail: 'Detailed Record View',
    basicInfo: 'Basic Information',
    refId: 'Reference ID',
    createdBy: 'Created By',
    createdTime: 'Submission Time',
    financialSummary: 'Financial Summary',
    openingBal: 'Opening Balance',
    closingBal: 'Closing Balance',
    auditTrace: 'Audit & Traceability',
    calcLogic: 'Calculation Formulas',
    formulaNet: 'Net Income = Total Sales - Total Expenses',
    formulaClosing: 'Closing Balance = Opening Balance + Net Income',
    formulaSales: 'Total Sales = Cash + Visa + Talabat + Credit',
    close: 'Close',
    viewDetail: 'View Detailed Report'
  },
  ar: {
    dashboard: 'لوحة التحكم',
    controlPanel: 'لوحة التحكم (البيانات)',
    reports: 'التقارير',
    systemSettings: 'إعدادات النظام',
    signOut: 'تسجيل الخروج',
    loggedInAs: 'مسجل كـ',
    headOffice: 'مسؤول المركز الرئيسي',
    branchUser: 'مستخدم فرع',
    revenue: 'إجمالي الإيرادات',
    costs: 'التكاليف التشغيلية',
    profit: 'صافي الربحية',
    margin: 'هامش الربح',
    history: 'اتجاهات الأداء الإقليمي',
    comparison: 'مقارنة الفروع المتعددة',
    aiAudit: 'تدقيق الذكاء الاصطناعي',
    settings: 'الإعدادات',
    language: 'اللغة',
    arabic: 'العربية',
    english: 'English',
    uaeTime: 'توقيت الإمارات',
    branchRanking: 'ترتيب أرباح الفروع',
    ledger: 'دفتر الأستاذ الأساسي',
    revenueStream: 'تدفق الإيرادات',
    commit: 'اعتماد البيان',
    export: 'تصدير CSV',
    print: 'طباعة PDF',
    dateRef: 'التاريخ / المرجع',
    origin: 'المصدر',
    status: 'الحالة',
    noData: 'لم يتم العثور على قيود دفتر الأستاذ',
    auditPass: 'اجتياز التدقيق',
    flagged: 'تم وضع علامة',
    salesBreakdown: 'تفصيل المبيعات',
    expenseBreakdown: 'تفصيل المصاريف',
    totalDailySales: 'إجمالي المبيعات اليومية',
    totalDailyExpenses: 'إجمالي المصاريف اليومية',
    recordDetail: 'عرض السجل التفصيلي',
    basicInfo: 'المعلومات الأساسية',
    refId: 'الرقم المرجعي',
    createdBy: 'أنشئ بواسطة',
    createdTime: 'وقت التقديم',
    financialSummary: 'الملخص المالي',
    openingBal: 'الرصيد الافتتاحي',
    closingBal: 'الرصيد الختامي',
    auditTrace: 'التدقيق والتتبع',
    calcLogic: 'معادلات الحساب',
    formulaNet: 'صافي الدخل = إجمالي المبيعات - إجمالي المصاريف',
    formulaClosing: 'الرصيد الختامي = الرصيد الافتتاحي + صافي الدخل',
    formulaSales: 'إجمالي المبيعات = نقداً + فيزا + طلبات + ائتمان',
    close: 'إغلاق',
    viewDetail: 'عرض التقرير التفصيلي'
  }
};
